### ISSUE TITLE
Tying swift-format to a SHA on main doesn't work

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#222] opened 2023-01-10 20:54 UTC
Or at least it didn't, because of [this practice](https://github.com/apple/swift-format/pull/459#discussion_r1047345742)
https://github.com/val-lang/val/actions/runs/3886903805/jobs/6633035274 failed.  

It looks like they may have adjusted that though; probably we need https://github.com/apple/swift-format/pull/467

**Comment by dabrahams** [comment] 2023-01-10 23:03
@lucteo the problem was suppressed by 8d1a31e but you should check to make sure it's a valid fix.

**Comment by dabrahams** [comment] 2023-01-11 19:07
Nope, that didn't work either: https://github.com/val-lang/val/actions/runs/3895800271/jobs/6651557388

**Comment by lucteo** [comment] 2023-01-11 20:04
Even though the commit SHA looks ok, and I can build the swift-format with that hash, it seems that CI build can't do that. Something eludes me for the moment.

Created https://github.com/val-lang/val/pull/224 as a quick workaround until the problem is fully investigated.

**Comment by peter-evans** [comment] 2024-01-08 11:44
Can this issue be closed now? I see that there is a new format check workflow here: https://github.com/hylo-lang/hylo/blob/main/.github/workflows/format-check.yml

**Comment by kyouko-taiga** [comment] 2024-01-08 12:39
@lucteo can we close?

**Comment by lucteo** [comment] 2024-01-10 20:18
I'm a bit out of touch with running swift-format on our project, but last I know it works ok. So, I think we can close this. Thank you very much.

**Closed** 2024-01-10 20:35 UTC
