### ISSUE TITLE
Constrained refinement doesn't parse

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1232] opened 2023-12-14 22:56 UTC
At 8bc61e0b:

```swift
trait A { type D }
trait B: A // error: expected '{'
  where    // error: unexpected token 'where'
    D: A {}
```

As a workaround, this passes:

```swift
trait A { type D }
trait B: A {
  type D: A
}
```

**Comment by kyouko-taiga** [comment] 2023-12-15 00:14
Duplicate of https://github.com/hylo-lang/hylo/issues/1112

**Closed by kyouko-taiga** 2023-12-15 00:14 UTC

**Comment by dabrahams** [comment] 2024-11-23 03:20
FWIW, the workaround doesn't work because the D's are different entities.
