### ISSUE TITLE
Generic if-let failurea

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1504] opened 2024-06-22 08:08 UTC
on requirements-machine

```
extension Optional where T: Movable {
  public fun postfix!() sink -> T {
    if let r: T = self { return r }
    else { fatal_error("force unwrapping nil") }
  }
}

public fun main() {
  let x = 42 as Optional<Int>
  print(x!) // fatal error
}
```

```
extension Optional where T: Movable {
  public fun postfix!() sink -> T {
    var me = self
    if let r: T = me { return r }
    else { fatal_error("force unwrapping nil") }
  }
}

public fun main() {
  let x = 42 as Optional<Int>
  print(x!) // prints garbage, for me
}
```

**Comment by kyouko-taiga** [comment] 2024-08-20 14:41
The issue is caused by the invalid synthesization of move initialization for union types, due to a broken way to compute discriminators. Given a union of type `Union<T, None<T>>` (i.e., the type of `Optional<T>`), where `T` is generic parameter, the compiler cannot currently guarantee that the discriminator identifying a payload of type `T` will be the same as the one identifying a payload of type `Int` in `Union<Int, None<Int>>`.

I have to think of a way to make the computation of discriminators blind to monomorphization.

**Comment by kyouko-taiga** [comment] 2024-08-20 14:52
Unions are currently handled using switch instructions in the IR. As a result, the problem is that we're "hardcoding" integers in the generic IR that will be invalidated by monomorphization. I suppose we could create a higher-level instruction specifically for switching over the different payloads. This instruction would be compiled down to a LLVM switch only after monomorphization.

One question remains: will this approach work with existentialization too?

**Closed** 2024-08-22 12:07 UTC
