### ISSUE TITLE
TypeChecker.swift:1849: Fatal error: infinite recursion

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1233] opened 2023-12-14 23:14 UTC
At 8bc61e0b, typecheck the following

```swift
trait CollectionCore {

  type Element
  type Index

  fun start_index() -> Index
  fun end_index() -> Index
  fun index(after i: Index) -> Index

  subscript(_ i: Index): Element { let }

  // A type that is wrapped to get the result of slicing
  type SliceCore
    = DefaultSliceCore<Self> // Default makes new Collections easier to define.

  // Not for user consumption; provides the implementation of slicing
  subscript slice_core(_ start: Index, _ end: Index): SliceCore { let }
}

// Adds slicing support requirements to CollectionCore.
trait Collection: CollectionCore {

  type SliceCore: CollectionCore where
    SliceCore.SliceCore == SliceCore

  // `Unsliced`: `Self == `Slice<U> ? U : Self`
  type Unsliced: CollectionCore
    where Unsliced.SliceCore == SliceCore,
          Unsliced.Element == SliceCore.Element,
          Unsliced.Index == SliceCore.Index

}

// Provide the user-consumed slicing operation.
extension Collection {

  typealias Unsliced = Self

  subscript(_ start: Index, _ end: Index): Slice<Unsliced> {
    yield Slice(core: self.sliceCore[start, end])
  }

}

// Wraps Unsliced_'s SliceCore as a full Collection.
type Slice<
  Unsliced_: CollectionCore
  where Unsliced_.SliceCore: CollectionCore,
        Unsliced_.SliceCore.SliceCore == Unsliced_.SliceCore,
        Unsliced_.SliceCore.Index == Unsliced_.Index,
        Unsliced_.SliceCore.Element == Unsliced_.Element
>: Collection
{

  memberwise init

  var core: SliceCore

  typealias Unsliced = Unsliced_

  // Prevents buildup of Slice<...> nesting.
  typealias SliceCore = Unsliced.SliceCore

  // Forward CollectionCore requirements to core
  typealias Element = SliceCore.Element
  typealias Index = SliceCore.Index
  fun start_index() -> Index { core.start_index() }
  fun end_index() -> Index { core.end_index() }
  fun index(after i: Index) -> Index {  core.index(after: i) }
  subscript(_ i: Index): Element { yield core[i] }

  subscript slice_core(_ start: Index, _ end: Index): SliceCore {
    yield core.slice_core[start, end]
  }

}

conformance Slice: Equatable where Unsliced.SliceCore: Equatable {}

//
// Conveniences so new Collections don't need to define their own slicing support.
//

extension Collection where SliceCore == DefaultSliceCore<Self> {

  subscript slice_core(_ start: Index, _ end: Index): SliceCore {
    yield DefaultSliceCore(base: self, start: start, end: end)
  }

}

type DefaultSliceCore<Base: CollectionCore>: CollectionCore  {

  let base: remote let Base
  var start: Index
  var end: Index

  typealias Element = Base.Element
  typealias Index = Base.Index

  fun start_index() -> Index { start }
  fun end_index() -> Index { end }
  fun index(after i: Index) -> Index { base.index(after: i) }

  subscript(_ i: Index): Element { yield base[i] }

  subscript slice_core(_ start: Index, _ end: Index): Self {
    yield Self(base: self.base, start: start, end: end)
  }

}

conformance DefaultSliceCore: Equatable where Base: Equatable, Index: Equatable {}

// ========= Demonstrations ============

// A simple collection using default slicing
type Basic: Collection, Equatable {

  typealias Element = String
  typealias Index = Int

  fun start_index() -> Index { 0 }
  fun end_index() -> Index { 10 }
  fun index(after i: Index) -> Index { i + 1 }

  subscript(_ i: Index): Element { yield String(i) }

}

 fun test_basic() {
  let basic = Basic()

  precondition(
    basic[3, 5] ==
      Slice<Basic>(
        core: DefaultSliceCore(base: basic, start: 3, end: 5)))

  precondition(basic[3, 5][3, 5] == basic[3, 5])
}

// A collection with a custom slice representation.
type CustomSliced: Collection, Equatable {

  typealias Element = UInt8
  typealias Index = Int

  fun start_index() -> Index { 0 }
  fun end_index() -> Index { 10 }
  fun index(after i: Index) -> Index { i + 1 }

  subscript(_ i: Index): Element { yield UInt8(i) }
  subscript slice_core(_ start: Index, _ end: Index): SliceCore {
    yield SliceCore(start: start, end: end)
  }

  type SliceCore: Collection, Equatable {

    typealias SliceCore = Self
    typealias Element = UInt8
    typealias Index = Int

    var start: Int
    var end: Int

    fun start_index() -> Index { start }
    fun end_index() -> Index { end }
    fun index(after i: Index) -> Index { i + 1 }

    subscript(_ i: Index): Element { yield UInt8(i) }

    subscript slice_core(_ start: Index, _ end: Index): SliceCore {
      yield Self(start: start, end: end)
    }
  }

}
```

**Comment by dabrahams** [comment] 2024-03-23 18:29
@kyouko-taiga This is still happening.  Any chance this can be triaged soon?

**Comment by kyouko-taiga** [comment] 2024-03-25 09:47
Can you try to reduce the size of your reproducer ?

**Comment by kyouko-taiga** [comment] 2024-03-29 14:59
The compiler won't crash anymore if you compile this program with #1416 but it will report quite many errors.

Since the reproducer is pretty big I think it'll be simpler to close this issue once #1416 is merge and open new ones for the other problems that your example surfaces.

**Comment by dabrahams** [comment] 2024-03-29 18:23
Yup

**Closed** 2024-03-29 18:23 UTC
